const dataVacancies = [
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Помощник администратора ресторана',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Подсобный рабочий',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Переводчик английского',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Курьер',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Помощник администратора ресторана',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Подсобный рабочий',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Переводчик английского',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Курьер',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Помощник администратора ресторана',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Подсобный рабочий',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Переводчик английского',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Курьер',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Помощник администратора ресторана',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Подсобный рабочий',
    salary: '300 BYN',
  },
  {
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Переводчик английского',
    salary: '300 BYN',
  },
  {
    id: 1,
    city: 'Минск',
    date: '15.12.2022',
    nameCompany: 'ООО «Белбриджес»',
    nameVacancy: 'Курьер',
    salary: '300 BYN',
  },
]

export default dataVacancies
